#!/usr/bin/env python3
"""Emit scripts/onboarding-welcome-lang-student-packs.json for patch-onboarding-welcome-lang-student-i18n.mjs."""
from __future__ import annotations

import json
from pathlib import Path

DIR = Path(__file__).resolve().parent
OUT = DIR / "onboarding-welcome-lang-student-packs.json"

# Locales already fully translated for WELCOME_SCREEN feature/how/trust blocks.
W_SKIP = frozenset({"de", "es", "fr", "pt"})


def w(
    trust_s: str,
    trust_t: str,
    trust_f: str,
    f1t: str,
    f1d: str,
    f2t: str,
    f2d: str,
    f3t: str,
    f3d: str,
    t1t: str,
    t1d: str,
    t2t: str,
    t2d: str,
    t3t: str,
    t3d: str,
    how: str,
    s1: str,
    s2: str,
    s3: str,
    th1: str,
    th2: str,
    th3: str,
) -> dict[str, str]:
    return {
        "TRUST_SECURE": trust_s,
        "TRUST_TIME": trust_t,
        "TRUST_FREE": trust_f,
        "FEAT1_TITLE": f1t,
        "FEAT1_DESC": f1d,
        "FEAT2_TITLE": f2t,
        "FEAT2_DESC": f2d,
        "FEAT3_TITLE": f3t,
        "FEAT3_DESC": f3d,
        "TUTOR_FEAT1_TITLE": t1t,
        "TUTOR_FEAT1_DESC": t1d,
        "TUTOR_FEAT2_TITLE": t2t,
        "TUTOR_FEAT2_DESC": t2d,
        "TUTOR_FEAT3_TITLE": t3t,
        "TUTOR_FEAT3_DESC": t3d,
        "HOW_LABEL": how,
        "HOW_STEP1": s1,
        "HOW_STEP2": s2,
        "HOW_STEP3": s3,
        "TUTOR_HOW_STEP1": th1,
        "TUTOR_HOW_STEP2": th2,
        "TUTOR_HOW_STEP3": th3,
    }


def s(
    goal_t: str,
    goal_sub: str,
    sec: str,
    gl: str,
    lvl: str,
    tl_row: str,
    tl_none: str,
    tl_by: str,
    lvl_ns: str,
    skip_link: str,
    skip_help: str,
    skip_prev: str,
) -> dict[str, str]:
    return {
        "GOAL_WIZARD_TITLE": goal_t,
        "GOAL_WIZARD_SUBTITLE": goal_sub,
        "PREVIEW_GOAL_LEVEL_SECTION": sec,
        "PREVIEW_GOAL": gl,
        "PREVIEW_CURRENT_LEVEL": lvl,
        "PREVIEW_TIMELINE_ROW": tl_row,
        "PREVIEW_TIMELINE_NOT_SET": tl_none,
        "PREVIEW_TIMELINE_BY_DATE": tl_by,
        "PREVIEW_LEVEL_NOT_SET": lvl_ns,
        "SKIP_GOAL_LINK": skip_link,
        "SKIP_GOAL_HELP": skip_help,
        "SKIP_GOAL_PREVIEW": skip_prev,
    }


def ls(sub: str, r1: str, r2: str, r3: str, r4: str, r5: str) -> dict[str, object]:
    return {"sub": sub, "rot": [r1, r2, r3, r4, r5]}


WELCOME: dict[str, dict[str, str]] = {
    "ar": w(
        "خاص وآمن",
        "يستغرق دقيقتين",
        "لا حاجة لبطاقة ائتمان للتسجيل",
        "اعثر على معلم",
        "تصفح معلمين موثوقين يتناسبون مع أهدافك وجدولك",
        "ابدأ الدرس",
        "انضم إلى دروس فيديو عالية الدقة من أي مكان وجهاز",
        "تابع تقدمك",
        "راقب تحسنك برؤى مدعومة بالذكاء الاصطناعي بعد كل درس",
        "حدد جدولك",
        "تحكم بوقت توفرك للتدريس",
        "درّس مباشرة",
        "دروس فيديو عالية الدقة مع أدوات تدريس مدمجة",
        "احصل على أجر",
        "اكسب وفق شروطك مع مدفوعات شفافة",
        "كيف يعمل",
        "أضبط ملفك",
        "اعثر على معلم",
        "ابدأ التعلم",
        "ابنِ ملفك",
        "حدد توفرك",
        "ابدأ التدريس",
    ),
    "cs": w(
        "Soukromé a bezpečné",
        "Zabere to 2 minuty",
        "K registraci nepotřebujete kreditní kartu",
        "Najděte lektora",
        "Prohlížejte ověřené lektory podle cílů a času",
        "Začněte lekci",
        "Připojte se k HD videohovorům odkudkoli a z jakéhokoli zařízení",
        "Sledujte pokrok",
        "Po každé lekci uvidíte zlepšení díky přehledům s AI",
        "Nastavte si rozvrh",
        "Určete, kdy můžete vyučovat",
        "Učte živě",
        "HD výuka s integrovanými nástroji",
        "Dostávejte výplatu",
        "Vydělávejte podle svých pravidel s transparentními platbami",
        "Jak to funguje",
        "Nastavte si profil",
        "Najděte lektora",
        "Začněte se učit",
        "Vytvořte profil",
        "Nastavte dostupnost",
        "Začněte vyučovat",
    ),
    "da": w(
        "Privat og sikkert",
        "Det tager 2 minutter",
        "Intet kreditkort kræves for at tilmelde dig",
        "Find en tutor",
        "Gennemse verificerede tutorer der matcher dine mål og din kalender",
        "Start lektion",
        "Deltag i HD-videolektioner hvor som helst, på enhver enhed",
        "Følg din fremgang",
        "Se din udvikling med AI-drevne indsigter efter hver lektion",
        "Sæt din tidsplan",
        "Styr hvornår du er tilgængelig til at undervise",
        "Undervis live",
        "HD-video med indbyggede undervisningsværktøjer",
        "Få udbetaling",
        "Tjen på dine præmisser med gennemsigtige udbetalinger",
        "Sådan virker det",
        "Opsæt din profil",
        "Find en tutor",
        "Begynd at lære",
        "Byg din profil",
        "Angiv tilgængelighed",
        "Begynd at undervise",
    ),
    "el": w(
        "Ιδιωτικό και ασφαλές",
        "Χρειάζεται 2 λεπτά",
        "Δεν απαιτείται πιστωτική κάρτα για εγγραφή",
        "Βρείτε καθηγητή",
        "Περιηγηθείτε σε επαληθευμένους καθηγητές που ταιριάζουν με τους στόχους και το πρόγραμμά σας",
        "Ξεκινήστε μάθημα",
        "Συμμετάσχετε σε μαθήματα βίντεο HD από παντού, σε οποιαδήποτε συσκευή",
        "Παρακολουθήστε την πρόοδο",
        "Δείτε τη βελτίωσή σας με πληροφορίες τροφοδοτούμενες από AI μετά από κάθε μάθημα",
        "Ορίστε το πρόγραμμά σας",
        "Ελέγξτε πότε είστε διαθέσιμοι για διδασκαλία",
        "Διδάξτε ζωντανά",
        "Μαθήματα βίντεο HD με ενσωματωμένα εργαλεία διδασκαλίας",
        "Λάβετε πληρωμή",
        "Κερδίστε με τους δικούς σας όρους με διαφανείς πληρωμές",
        "Πώς λειτουργεί",
        "Ρυθμίστε το προφίλ σας",
        "Βρείτε καθηγητή",
        "Ξεκινήστε να μαθαίνετε",
        "Χτίστε το προφίλ σας",
        "Ορίστε διαθεσιμότητα",
        "Ξεκινήστε να διδάσκετε",
    ),
    "fa": w(
        "خصوصی و امن",
        "فقط دو دقیقه طول می‌کشد",
        "برای ثبت‌نام به کارت اعتباری نیاز نیست",
        "معلم پیدا کنید",
        "میان معلم‌های تأییدشده بگردید که با اهداف و برنامهٔ شما هماهنگ‌اند",
        "درس را شروع کنید",
        "به کلاس‌های ویدیویی HD از هر جا و هر دستگاهی بپیوندید",
        "پیشرفت را دنبال کنید",
        "بعد از هر درس با بینش‌های مبتنی بر هوش مصنوعی بهبود خود را ببینید",
        "برنامهٔ خود را تنظیم کنید",
        "زمان در دسترس بودن برای تدریس را کنترل کنید",
        "زنده تدریس کنید",
        "کلاس‌های ویدیویی HD با ابزارهای آموزشی داخلی",
        "درآمد بگیرید",
        "با پرداخت‌های شفاف، مطابق شرایط خود درآمد کسب کنید",
        "چطور کار می‌کند",
        "پروفایل خود را تنظیم کنید",
        "معلم پیدا کنید",
        "یادگیری را شروع کنید",
        "پروفایل بسازید",
        "دسترسی‌تان را مشخص کنید",
        "تدریس را شروع کنید",
    ),
    "fi": w(
        "Yksityinen ja turvallinen",
        "Kestää 2 minuuttia",
        "Luottokorttia ei tarvita rekisteröitymiseen",
        "Löydä tutor",
        "Selaa vahvistettuja tutoreita, jotka sopivat tavoitteisiisi ja aikatauluusi",
        "Aloita oppitunti",
        "Liity HD-videotunneille mistä tahansa, millä tahansa laitteella",
        "Seuraa edistymistä",
        "Näe kehityksesi tekoälypohjaisilla oivalluksilla jokaisen tunnin jälkeen",
        "Aseta aikataulusi",
        "Hallitse milloin olet tavoitettavissa opettamiseen",
        "Opeta livenä",
        "HD-videotunnit sisäänrakennetuin opetusvälinein",
        "Saa maksuja",
        "Ansaitse omilla ehdoillasi läpinäkyvillä maksuilla",
        "Näin se toimii",
        "Tee profiilisi",
        "Löydä tutor",
        "Aloita oppiminen",
        "Rakenna profiilisi",
        "Määritä saatavuus",
        "Aloita opettaminen",
    ),
    "he": w(
        "פרטי ומאובטח",
        "לוקח שתי דקות",
        "אין צורך בכרטיס אשראי כדי להירשם",
        "מצאו מורה פרטי",
        "עיינו במורים מאומתים שמתאימים למטרות וללוח הזמנים שלכם",
        "התחילו שיעור",
        "הצטרפו לשיעורי וידאו באיכות HD מכל מקום, בכל מכשיר",
        "עקבו אחרי ההתקדמות",
        "ראו את השיפור שלכם עם תובנות מבוססות בינה מלאכותית אחרי כל שיעור",
        "קבעו את לוח הזמנים",
        "שלטו מתי אתם זמינים ללמד",
        "למדו בשידור חי",
        "שיעורי וידאו HD עם כלי הוראה מובנים",
        "קבלו תשלום",
        "הרוויחו בתנאים שלכם עם תשלומים שקופים",
        "איך זה עובד",
        "הגדירו את הפרופיל",
        "מצאו מורה",
        "התחילו ללמוד",
        "בנו פרופיל",
        "הגדירו זמינות",
        "התחילו ללמד",
    ),
    "hi": w(
        "निजी और सुरक्षित",
        "2 मिनट लगते हैं",
        "साइन अप के लिए क्रेडिट कार्ड की ज़रूरत नहीं",
        "ट्यूटर खोजें",
        "अपने लक्ष्यों और समय के अनुसार सत्यापित ट्यूटर देखें",
        "पाठ शुरू करें",
        "कहीं से भी, किसी भी डिवाइस पर HD वीडियो पाठ में शामिल हों",
        "प्रगति ट्रैक करें",
        "हर पाठ के बाद AI आधारित अंतर्दृष्टि से सुधार देखें",
        "अपना शेड्यूल सेट करें",
        "जब आप पढ़ाने के लिए उपलब्ध हैं, नियंत्रित करें",
        "लाइव पढ़ाएं",
        "अंतर्निहित शिक्षण उपकरणों के साथ HD वीडियो पाठ",
        "भुगतान पाएं",
        "पारदर्शी भुगतान के साथ अपनी शर्तों पर कमाएँ",
        "यह कैसे काम करता है",
        "अपनी प्रोफ़ाइल सेट करें",
        "ट्यूटर खोजें",
        "सीखना शुरू करें",
        "प्रोफ़ाइल बनाएं",
        "उपलब्धता सेट करें",
        "पढ़ाना शुरू करें",
    ),
    "id": w(
        "Privat dan aman",
        "Hanya 2 menit",
        "Tidak perlu kartu kredit untuk mendaftar",
        "Cari tutor",
        "Jelajahi tutor terverifikasi yang sesuai tujuan dan jadwal Anda",
        "Mulai pelajaran",
        "Ikuti pelajaran video HD dari mana saja, di perangkat apa pun",
        "Lacak kemajuan",
        "Lihat peningkatan Anda dengan wawasan berbasis AI setelah setiap pelajaran",
        "Atur jadwal Anda",
        "Kendalikan kapan Anda tersedia mengajar",
        "Mengajar secara langsung",
        "Pelajaran video HD dengan alat mengajar bawaan",
        "Dapatkan bayaran",
        "Hasilkan sesuai syarat Anda dengan pembayaran transparan",
        "Cara kerjanya",
        "Siapkan profil Anda",
        "Cari tutor",
        "Mulai belajar",
        "Bangun profil Anda",
        "Atur ketersediaan",
        "Mulai mengajar",
    ),
    "it": w(
        "Privato e sicuro",
        "Richiede 2 minuti",
        "Nessuna carta di credito per registrarsi",
        "Trova un tutor",
        "Sfoglia tutor verificati in linea con obiettivi e orari",
        "Inizia una lezione",
        "Partecipa a lezioni video HD ovunque, su qualsiasi dispositivo",
        "Monitora i progressi",
        "Vedi i miglioramenti con approfondimenti basati sull'IA dopo ogni lezione",
        "Imposta il tuo calendario",
        "Decidi quando sei disponibile a insegnare",
        "Insegna dal vivo",
        "Lezioni video HD con strumenti didattici integrati",
        "Ricevi pagamenti",
        "Guadagna alle tue condizioni con pagamenti trasparenti",
        "Come funziona",
        "Configura il profilo",
        "Trova un tutor",
        "Inizia a imparare",
        "Crea il profilo",
        "Imposta la disponibilità",
        "Inizia a insegnare",
    ),
    "ja": w(
        "プライベートで安全",
        "所要時間は約2分",
        "登録にクレジットカードは不要です",
        "チューターを見つける",
        "目標とスケジュールに合う認定チューターを探す",
        "レッスンを始める",
        "どこからでも、どの端末でもHDビデオレッスンに参加",
        "進捗を確認",
        "各レッスン後にAIのインサイトで上達を可視化",
        "スケジュールを設定",
        "指導可能な時間を自分で管理",
        "ライブで教える",
        "教材ツール付きのHDビデオレッスン",
        "報酬を受け取る",
        "透明な支払いで自分のペースで収入を得る",
        "仕組み",
        "プロフィールを設定",
        "チューターを見つける",
        "学習を始める",
        "プロフィールを作る",
        "空き時間を設定",
        "指導を始める",
    ),
    "ko": w(
        "비공개이며 안전합니다",
        "2분이면 됩니다",
        "가입에 신용카드가 필요하지 않습니다",
        "튜터 찾기",
        "목표와 일정에 맞는 인증 튜터를 둘러보세요",
        "수업 시작하기",
        "어디서나 어떤 기기로든 HD 화상 수업에 참여하세요",
        "진행 상황 추적",
        "매 수업 후 AI 기반 인사이트로 향상도를 확인하세요",
        "일정 설정하기",
        "언제 가르칠 수 있는지 직접 관리하세요",
        "라이브로 가르치기",
        "내장된 수업 도구가 있는 HD 화상 수업",
        "수익 받기",
        "투명한 정산으로 내 조건에 맞게 수익을 올리세요",
        "이용 방법",
        "프로필 설정",
        "튜터 찾기",
        "학습 시작하기",
        "프로필 만들기",
        "가능 시간 설정",
        "가르치기 시작",
    ),
    "ms": w(
        "Peribadi dan selamat",
        "Hanya 2 minit",
        "Tiada kad kredit diperlukan untuk mendaftar",
        "Cari tutor",
        "Layari tutor disahkan yang sepadan dengan matlamat dan jadual anda",
        "Mulakan pelajaran",
        "Sertai pelajaran video HD dari mana-mana, pada mana-mana peranti",
        "Jejaki kemajuan",
        "Lihat peningkatan anda dengan panduan dikuasakan AI selepas setiap pelajaran",
        "Tetapkan jadual anda",
        "Kawal bila anda tersedia untuk mengajar",
        "Mengajar secara langsung",
        "Pelajaran video HD dengan alat pengajaran terbina dalam",
        "Dapatkan bayaran",
        "Pendapatan mengikut terma anda dengan bayaran telus",
        "Bagaimana ia berfungsi",
        "Sediakan profil anda",
        "Cari tutor",
        "Mula belajar",
        "Bina profil anda",
        "Tetapkan ketersediaan",
        "Mula mengajar",
    ),
    "nl": w(
        "Privé en veilig",
        "Duurt 2 minuten",
        "Geen creditcard nodig om je aan te melden",
        "Vind een tutor",
        "Blader door geverifieerde tutors die bij je doelen en planning passen",
        "Start een les",
        "Doe mee aan HD-videolessen, overal, op elk apparaat",
        "Volg je voortgang",
        "Zie je verbetering met AI-inzichten na elke les",
        "Stel je rooster in",
        "Bepaal wanneer je beschikbaar bent om te geven",
        "Geef live les",
        "HD-videolessen met ingebouwde tools",
        "Word betaald",
        "Verdien op jouw voorwaarden met transparante uitbetalingen",
        "Zo werkt het",
        "Stel je profiel in",
        "Vind een tutor",
        "Begin met leren",
        "Bouw je profiel op",
        "Stel beschikbaarheid in",
        "Begin met lesgeven",
    ),
    "no": w(
        "Privat og trygt",
        "Tar 2 minutter",
        "Ingen kredittkort kreves for å registrere deg",
        "Finn en veileder",
        "Utforsk verifiserte veiledere som matcher målene og timeplanen din",
        "Start leksjon",
        "Bli med på HD-videoundervisning hvor som helst, på hvilken som helst enhet",
        "Følg fremgangen",
        "Se forbedringen med AI-drevne innsikter etter hver leksjon",
        "Sett timeplanen din",
        "Styr når du er tilgjengelig for undervisning",
        "Undervis live",
        "HD-video med innebygde undervisningsverktøy",
        "Få utbetaling",
        "Tjen på dine premisser med transparente utbetalinger",
        "Slik fungerer det",
        "Sett opp profilen din",
        "Finn en veileder",
        "Begynn å lære",
        "Bygg profilen din",
        "Angi tilgjengelighet",
        "Begynn å undervise",
    ),
    "pl": w(
        "Prywatnie i bezpiecznie",
        "Zajmuje 2 minuty",
        "Do rejestracji nie potrzebujesz karty kredytowej",
        "Znajdź korepetytora",
        "Przeglądaj zweryfikowanych korepetytorów dopasowanych do celów i harmonogramu",
        "Rozpocznij lekcję",
        "Dołącz do lekcji wideo HD z dowolnego miejsca i urządzenia",
        "Śledź postępy",
        "Zobacz swoją poprawę dzięki analizom wspieranym przez AI po każdej lekcji",
        "Ustal swój harmonogram",
        "Kontroluj, kiedy możesz uczyć",
        "Ucz na żywo",
        "Lekcje wideo HD z wbudowanymi narzędziami",
        "Otrzymuj wynagrodzenie",
        "Zarabiaj na swoich zasadach z przejrzystymi wypłatami",
        "Jak to działa",
        "Skonfiguruj profil",
        "Znajdź korepetytora",
        "Zacznij się uczyć",
        "Zbuduj profil",
        "Ustaw dostępność",
        "Zacznij uczyć",
    ),
    "ro": w(
        "Privat și sigur",
        "Durează 2 minute",
        "Nu este nevoie de card pentru înscriere",
        "Găsește un tutor",
        "Răsfoiește tutori verificați potriviți obiectivelor și programului tău",
        "Începe lecția",
        "Participă la lecții video HD de oriunde, pe orice dispozitiv",
        "Urmărește progresul",
        "Vezi îmbunătățirea cu perspective bazate pe AI după fiecare lecție",
        "Stabilește programul",
        "Controlează când ești disponibil să predai",
        "Predă live",
        "Lecții video HD cu instrumente integrate",
        "Primește plata",
        "Câștigă în termenii tăi cu plăți transparente",
        "Cum funcționează",
        "Configurează profilul",
        "Găsește un tutor",
        "Începe să înveți",
        "Construiește profilul",
        "Setează disponibilitatea",
        "Începe să predai",
    ),
    "ru": w(
        "Конфиденциально и безопасно",
        "Займёт 2 минуты",
        "Для регистрации не нужна банковская карта",
        "Найдите репетитора",
        "Просматривайте проверенных репетиторов под ваши цели и расписание",
        "Начните урок",
        "Подключайтесь к HD‑видеоурокам откуда угодно и с любого устройства",
        "Отслеживайте прогресс",
        "Смотрите прогресс с аналитикой на базе ИИ после каждого урока",
        "Настройте расписание",
        "Управляйте временем доступности для преподавания",
        "Преподавайте онлайн",
        "HD‑видеоуроки со встроенными инструментами",
        "Получайте оплату",
        "Зарабатывайте на своих условиях с прозрачными выплатами",
        "Как это работает",
        "Настройте профиль",
        "Найдите репетитора",
        "Начните учиться",
        "Создайте профиль",
        "Укажите доступность",
        "Начните преподавать",
    ),
    "sv": w(
        "Privat och säkert",
        "Tar 2 minuter",
        "Inget kreditkort krävs för att registrera dig",
        "Hitta en handledare",
        "Bläddra bland verifierade handledare som matchar dina mål och ditt schema",
        "Starta lektion",
        "Gå med i HD‑videolektioner var som helst, på vilken enhet som helst",
        "Följ framstegen",
        "Se din utveckling med AI‑drivna insikter efter varje lektion",
        "Ställ in ditt schema",
        "Styr när du är tillgänglig att undervisa",
        "Undervisa live",
        "HD‑videolektioner med inbyggda verktyg",
        "Få betalt",
        "Tjäna på dina villkor med transparenta utbetalningar",
        "Så funkar det",
        "Sätt upp din profil",
        "Hitta en handledare",
        "Börja lära dig",
        "Bygg din profil",
        "Ange tillgänglighet",
        "Börja undervisa",
    ),
    "th": w(
        "เป็นส่วนตัวและปลอดภัย",
        "ใช้เวลา 2 นาที",
        "ไม่ต้องใช้บัตรเครดิตในการสมัคร",
        "ค้นหาติวเตอร์",
        "เรียกดูติวเตอร์ที่ยืนยันแล้วให้ตรงกับเป้าหมายและตารางของคุณ",
        "เริ่มบทเรียน",
        "เข้าร่วมบทเรียนวิดีโอ HD ได้ทุกที่บนอุปกรณ์ใดก็ได้",
        "ติดตามความคืบหน้า",
        "เห็นความก้าวหน้าด้วยข้อมูลเชิงลึกจาก AI หลังทุกบทเรียน",
        "ตั้งตารางเวลาของคุณ",
        "กำหนดเวลาที่พร้อมสอน",
        "สอนสด",
        "บทเรียนวิดีโอ HD พร้อมเครื่องมือสอนในตัว",
        "รับค่าตอบแทน",
        "สร้างรายได้ตามเงื่อนไขของคุณด้วยการจ่ายเงินที่โปร่งใส",
        "วิธีการทำงาน",
        "ตั้งค่าโปรไฟล์ของคุณ",
        "ค้นหาติวเตอร์",
        "เริ่มเรียน",
        "สร้างโปรไฟล์",
        "ตั้งค่าความพร้อม",
        "เริ่มสอน",
    ),
    "tr": w(
        "Gizli ve güvenli",
        "2 dakika sürer",
        "Kayıt için kredi kartı gerekmez",
        "Eğitmen bulun",
        "Hedeflerinize ve programınıza uyan doğrulanmış eğitmenlere göz atın",
        "Derse başlayın",
        "Her yerden, her cihazdan HD video derslerine katılın",
        "İlerlemenizi takip edin",
        "Her dersten sonra yapay zekâ destekli içgörülerle gelişiminizi görün",
        "Programınızı ayarlayın",
        "Ne zaman müsait olduğunuzu kontrol edin",
        "Canlı öğretin",
        "Yerleşik araçlarla HD video dersleri",
        "Ödeme alın",
        "Şeffaf ödemelerle kendi koşullarınızda kazanın",
        "Nasıl çalışır",
        "Profilinizi oluşturun",
        "Eğitmen bulun",
        "Öğrenmeye başlayın",
        "Profilinizi oluşturun",
        "Müsaitliği belirleyin",
        "Öğretmeye başlayın",
    ),
    "uk": w(
        "Приватно й безпечно",
        "Займає 2 хвилини",
        "Для реєстрації не потрібна банківська карта",
        "Знайдіть репетитора",
        "Переглядайте перевірених репетиторів під ваші цілі та розклад",
        "Почніть урок",
        "Долучайтеся до HD‑відеоуроків звідусіль і з будь‑якого пристрою",
        "Відстежуйте прогрес",
        "Бачте покращення з аналітикою на базі ШІ після кожного уроку",
        "Налаштуйте розклад",
        "Керуйте часом доступності для викладання",
        "Викладайте наживо",
        "HD‑відеоуроки з вбудованими інструментами",
        "Отримуйте оплату",
        "Заробляйте на своїх умовах із прозорими виплатами",
        "Як це працює",
        "Налаштуйте профіль",
        "Знайдіть репетитора",
        "Почніть навчатися",
        "Створіть профіль",
        "Вкажіть доступність",
        "Почніть викладати",
    ),
    "vi": w(
        "Riêng tư và an toàn",
        "Chỉ mất 2 phút",
        "Không cần thẻ tín dụng để đăng ký",
        "Tìm gia sư",
        "Duyệt các gia sư đã xác minh phù hợp mục tiêu và lịch của bạn",
        "Bắt đầu buổi học",
        "Tham gia học video HD mọi lúc, mọi thiết bị",
        "Theo dõi tiến độ",
        "Xem sự tiến bộ với thông tin chi tiết bằng AI sau mỗi buổi học",
        "Đặt lịch của bạn",
        "Kiểm soát khi nào bạn sẵn sàng dạy",
        "Dạy trực tiếp",
        "Buổi học video HD kèm công cụ dạy học tích hợp",
        "Nhận thanh toán",
        "Kiếm tiền theo điều kiện của bạn với thanh toán minh bạch",
        "Cách hoạt động",
        "Thiết lập hồ sơ",
        "Tìm gia sư",
        "Bắt đầu học",
        "Xây dựng hồ sơ",
        "Đặt lịch rảnh",
        "Bắt đầu dạy",
    ),
    "zh": w(
        "私密且安全",
        "只需约 2 分钟",
        "注册无需信用卡",
        "寻找导师",
        "浏览通过验证、符合目标与日程的导师",
        "开始上课",
        "随时随地用任意设备加入高清视频课",
        "跟踪进度",
        "每节课后通过 AI 洞察查看提升情况",
        "设置你的时间安排",
        "自主控制可授课时间",
        "直播授课",
        "内置教学工具的高清视频课",
        "获得报酬",
        "以透明结算按你的方式获得收入",
        "运作方式",
        "完善个人资料",
        "寻找导师",
        "开始学习",
        "建立个人资料",
        "设置可授课时间",
        "开始授课",
    ),
}

STUDENT: dict[str, dict[str, str]] = {
    "ar": s(
        "ما هدفك؟",
        "يساعدنا ذلك على إنشاء مسار تعلم مخصص لك.",
        "الهدف والمستوى",
        "الهدف",
        "المستوى الحالي",
        "الجدول الزمني",
        "لا يوجد تاريخ مستهدف بعد",
        "بحلول {{date}}",
        "غير محدد — يمكنك إضافته لاحقاً من ملفك",
        "سأبدأ بتجربة درس",
        "يمكنك تخطي الهدف الآن وإضافته لاحقاً من ملفك، وسنبني خطة عندها.",
        "أتعلم بوتيرتي الخاصة",
    ),
    "cs": s(
        "Jaký je váš cíl?",
        "Pomůže nám vytvořit personalizovanou studijní cestu.",
        "Cíl a úroveň",
        "Cíl",
        "Současná úroveň",
        "Časový rámec",
        "Zatím bez cílového data",
        "Do {{date}}",
        "Nevybráno — doplníte později v profilu",
        "Začnu zkusit lekci",
        "Cíl teď přeskočíte a kdykoli ho doplníte v profilu; pak sestavíme plán.",
        "Učím se vlastním tempem",
    ),
    "da": s(
        "Hvad er dit mål?",
        "Det hjælper os med at lave en personlig læringssti til dig.",
        "Mål og niveau",
        "Mål",
        "Nuværende niveau",
        "Tidsramme",
        "Intet måldato endnu",
        "Senest {{date}}",
        "Ikke valgt — kan tilføjes senere i din profil",
        "Jeg starter med at prøve en lektion",
        "Spring målet over nu. Du kan tilføje det når som helst i din profil, så bygger vi en plan.",
        "Lærer i mit eget tempo",
    ),
    "de": s(
        "Was ist dein Ziel?",
        "So erstellen wir einen persönlichen Lernpfad für dich.",
        "Ziel & Niveau",
        "Ziel",
        "Aktuelles Niveau",
        "Zeitrahmen",
        "Noch kein Zieldatum",
        "Bis {{date}}",
        "Nicht gewählt — später im Profil ergänzbar",
        "Ich starte mit einer Probestunde",
        "Ziel vorerst überspringen. Du kannst es jederzeit im Profil ergänzen — dann erstellen wir eine Roadmap.",
        "Lerne in meinem eigenen Tempo",
    ),
    "el": s(
        "Ποιος είναι ο στόχος σας;",
        "Μας βοηθά να δημιουργήσουμε μια εξατομικευμένη διαδρομή μάθησης.",
        "Στόχος και επίπεδο",
        "Στόχος",
        "Τρέχον επίπεδο",
        "Χρονοδιάγραμμα",
        "Δεν έχει οριστεί ακόμη ημερομηνία-στόχος",
        "Έως {{date}}",
        "Δεν επιλέχθηκε — μπορείτε να το προσθέσετε αργότερα από το προφίλ",
        "Θα ξεκινήσω δοκιμάζοντας ένα μάθημα",
        "Παραλείψτε τον στόχο τώρα. Μπορείτε να τον προσθέσετε οποτεδήποτε από το προφίλ και τότε θα φτιάξουμε πλάνο.",
        "Μαθαίνω με τον δικό μου ρυθμό",
    ),
    "es": s(
        "¿Cuál es tu objetivo?",
        "Nos ayuda a crear una ruta de aprendizaje personalizada.",
        "Objetivo y nivel",
        "Objetivo",
        "Nivel actual",
        "Plazo",
        "Aún sin fecha objetivo",
        "Para el {{date}}",
        "Sin seleccionar: puedes añadirlo luego en tu perfil",
        "Empezaré probando una clase",
        "Omite el objetivo por ahora. Puedes añadirlo cuando quieras desde tu perfil y crearemos un plan.",
        "Aprendo a mi ritmo",
    ),
    "fa": s(
        "هدف شما چیست؟",
        "به ما کمک می‌کند مسیر یادگیری شخصی‌سازی‌شده بسازیم.",
        "هدف و سطح",
        "هدف",
        "سطح فعلی",
        "زمان‌بندی",
        "هنوز تاریخ هدف تعیین نشده",
        "تا {{date}}",
        "انتخاب نشده — بعداً از پروفایل می‌توانید اضافه کنید",
        "اول با یک درس شروع می‌کنم",
        "فعلاً هدف را رد کنید؛ هر زمان از پروفایل می‌توانید اضافه کنید و آن‌وقت نقشه می‌سازیم.",
        "با سرعت خودم یاد می‌گیرم",
    ),
    "fi": s(
        "Mikä on tavoitteesi?",
        "Auttaa meitä luomaan sinulle henkilökohtaisen oppimispolun.",
        "Tavoite ja taso",
        "Tavoite",
        "Nykyinen taso",
        "Aikataulu",
        "Ei vielä tavoitepäivää",
        "Mennessä {{date}}",
        "Ei valittu — voit lisätä myöhemmin profiilista",
        "Aloitan kokeilemalla oppituntia",
        "Ohita tavoite toistaiseksi. Voit lisätä sen milloin tahansa profiilista, ja rakennamme suunnitelman silloin.",
        "Opin omaan tahtiini",
    ),
    "fr": s(
        "Quel est votre objectif ?",
        "Cela nous aide à créer un parcours d'apprentissage personnalisé.",
        "Objectif et niveau",
        "Objectif",
        "Niveau actuel",
        "Échéance",
        "Pas encore de date cible",
        "D'ici le {{date}}",
        "Non sélectionné — vous pourrez l'ajouter plus tard dans votre profil",
        "Je commence par essayer une leçon",
        "Ignorez l'objectif pour l'instant. Vous pourrez l'ajouter à tout moment depuis votre profil, et nous construirons un plan.",
        "J'apprends à mon rythme",
    ),
    "he": s(
        "מה המטרה שלך?",
        "זה עוזר לנו ליצור מסלל למידה מותאם אישית.",
        "מטרה ורמה",
        "מטרה",
        "רמה נוכחית",
        "לוח זמנים",
        "עדיין אין תאריך יעד",
        "עד {{date}}",
        "לא נבחר — אפשר להוסיף מאוחר יותר מהפרופיל",
        "אתחיל בנסיון שיעור",
        "דלגו על המטרה לעת עתה. תוכלו להוסיף בכל עת מהפרופיל, ואז נבנה מפת דרכים.",
        "לומדים בקצב שלי",
    ),
    "hi": s(
        "आपका लक्ष्य क्या है?",
        "इससे हम आपके लिए व्यक्तिगत सीखने का रास्ता बना सकते हैं।",
        "लक्ष्य और स्तर",
        "लक्ष्य",
        "वर्तमान स्तर",
        "समयसीमा",
        "अभी तक कोई लक्ष्य तिथि नहीं",
        "{{date}} तक",
        "चयनित नहीं — बाद में प्रोफ़ाइल से जोड़ सकते हैं",
        "मैं पाठ आज़मा कर शुरू करूँगा/करूँगी",
        "अभी लक्ष्य छोड़ें। कभी भी प्रोफ़ाइल से जोड़ सकते हैं, तब हम रोडमैप बनाएंगे।",
        "अपनी गति से सीख रहा/रही हूँ",
    ),
    "id": s(
        "Apa tujuanmu?",
        "Ini membantu kami membuat jalur belajar yang dipersonalisasi.",
        "Tujuan & level",
        "Tujuan",
        "Level saat ini",
        "Linimasa",
        "Belum ada tanggal target",
        "Pada {{date}}",
        "Belum dipilih — bisa ditambahkan nanti dari profil",
        "Saya mulai dengan mencoba pelajaran",
        "Lewati tujuan dulu. Anda bisa menambahkannya kapan saja dari profil, lalu kami buat peta perjalanan.",
        "Belajar dengan ritme saya sendiri",
    ),
    "it": s(
        "Qual è il tuo obiettivo?",
        "Ci aiuta a creare un percorso di apprendimento personalizzato.",
        "Obiettivo e livello",
        "Obiettivo",
        "Livello attuale",
        "Tempistiche",
        "Nessuna data obiettivo ancora",
        "Entro il {{date}}",
        "Non selezionato — puoi aggiungerlo più tardi dal profilo",
        "Inizio provando una lezione",
        "Salta l'obiettivo per ora. Potrai aggiungerlo quando vuoi dal profilo e creeremo un piano.",
        "Imparo al mio ritmo",
    ),
    "ja": s(
        "目標は何ですか？",
        "あなた専用の学習パスを作るために役立ちます。",
        "目標とレベル",
        "目標",
        "現在のレベル",
        "スケジュール",
        "まだ目標日はありません",
        "{{date}} まで",
        "未選択 — 後からプロフィールで追加できます",
        "まずはレッスンを試します",
        "今は目標をスキップできます。いつでもプロフィールから追加でき、そのときにロードマップを作成します。",
        "自分のペースで学んでいます",
    ),
    "ko": s(
        "목표가 무엇인가요?",
        "맞춤 학습 경로를 만드는 데 도움이 됩니다.",
        "목표와 수준",
        "목표",
        "현재 수준",
        "일정",
        "아직 목표 날짜 없음",
        "{{date}}까지",
        "선택 안 함 — 나중에 프로필에서 추가할 수 있어요",
        "먼저 수업을 체험해 볼게요",
        "지금은 목표를 건너뛸 수 있어요. 언제든 프로필에서 추가하면 그때 로드맵을 만들어 드려요.",
        "제 속도로 배우고 있어요",
    ),
    "ms": s(
        "Apakah matlamat anda?",
        "Ini membantu kami membina laluan pembelajaran peribadi.",
        "Matlamat & tahap",
        "Matlamat",
        "Tahap semasa",
        "Garis masa",
        "Tiada tarikh sasaran lagi",
        "Menjelang {{date}}",
        "Tidak dipilih — boleh ditambah kemudian dari profil",
        "Saya mula dengan mencuba pelajaran",
        "Langkau matlamat buat masa ini. Anda boleh menambahnya bila-bila masa dari profil, dan kami akan bina pelan.",
        "Belajar mengikut rentak saya",
    ),
    "nl": s(
        "Wat is je doel?",
        "Zo maken we een persoonlijk leerpad voor je.",
        "Doel en niveau",
        "Doel",
        "Huidig niveau",
        "Tijdlijn",
        "Nog geen streefdatum",
        "Tegen {{date}}",
        "Niet gekozen — later toe te voegen vanuit je profiel",
        "Ik begin met een les proberen",
        "Sla het doel nu over. Je kunt het altijd in je profiel toevoegen; dan maken we een plan.",
        "Ik leer in mijn eigen tempo",
    ),
    "no": s(
        "Hva er målet ditt?",
        "Det hjelper oss å lage en personlig læringssti.",
        "Mål og nivå",
        "Mål",
        "Nåværende nivå",
        "Tidslinje",
        "Ingen måldato ennå",
        "Innen {{date}}",
        "Ikke valgt — kan legges til senere i profilen",
        "Jeg starter med å prøve en leksjon",
        "Hopp over målet nå. Du kan legge det til når som helst fra profilen, så lager vi en plan.",
        "Lærer i eget tempo",
    ),
    "pl": s(
        "Jaki jest Twój cel?",
        "Pomaga nam to stworzyć spersonalizowaną ścieżkę nauki.",
        "Cel i poziom",
        "Cel",
        "Obecny poziom",
        "Harmonogram",
        "Brak daty docelowej",
        "Do {{date}}",
        "Nie wybrano — możesz dodać później w profilu",
        "Zacznę od wypróbowania lekcji",
        "Pomiń cel na razie. Dodasz go w każdej chwili w profilu, a wtedy zbudujemy plan.",
        "Uczę się we własnym tempie",
    ),
    "pt": s(
        "Qual é o seu objetivo?",
        "Ajuda-nos a criar um percurso de aprendizagem personalizado.",
        "Objetivo e nível",
        "Objetivo",
        "Nível atual",
        "Prazo",
        "Ainda sem data alvo",
        "Até {{date}}",
        "Não selecionado — pode adicionar depois no perfil",
        "Vou começar experimentando uma aula",
        "Ignore o objetivo por agora. Pode adicioná-lo a qualquer momento no perfil e criaremos um plano.",
        "Aprendo no meu ritmo",
    ),
    "ro": s(
        "Care este obiectivul tău?",
        "Ne ajută să creăm o cale de învățare personalizată.",
        "Obiectiv și nivel",
        "Obiectiv",
        "Nivel curent",
        "Cronologie",
        "Încă fără dată țintă",
        "Până la {{date}}",
        "Neselectat — poți adăuga mai târziu din profil",
        "Încep încercând o lecție",
        "Sari peste obiectiv acum. Îl poți adăuga oricând din profil, iar atunci construim un plan.",
        "Învăț în ritmul meu",
    ),
    "ru": s(
        "Какая у вас цель?",
        "Это помогает нам создать персональную траекторию обучения.",
        "Цель и уровень",
        "Цель",
        "Текущий уровень",
        "Сроки",
        "Целевая дата пока не указана",
        "К {{date}}",
        "Не выбрано — можно добавить позже в профиле",
        "Начну с пробного урока",
        "Пока пропустите цель. Её можно добавить в любой момент в профиле — тогда мы построим план.",
        "Учусь в своём темпе",
    ),
    "sv": s(
        "Vad är ditt mål?",
        "Det hjälper oss att skapa en personlig inlärningsväg.",
        "Mål och nivå",
        "Mål",
        "Nuvarande nivå",
        "Tidslinje",
        "Inget måldatum ännu",
        "Senast {{date}}",
        "Inte valt — kan läggas till senare i profilen",
        "Jag börjar med att prova en lektion",
        "Hoppa över målet nu. Du kan lägga till det när som helst i profilen, då bygger vi en plan.",
        "Jag lär i min egen takt",
    ),
    "th": s(
        "เป้าหมายของคุณคืออะไร?",
        "ช่วยให้เราสร้างเส้นทางการเรียนรู้เฉพาะบุคคล",
        "เป้าหมายและระดับ",
        "เป้าหมาย",
        "ระดับปัจจุบัน",
        "ไทม์ไลน์",
        "ยังไม่มีวันเป้าหมาย",
        "ภายใน {{date}}",
        "ยังไม่ได้เลือก — เพิ่มทีหลังในโปรไฟล์ได้",
        "ฉันจะเริ่มจากลองเรียนครั้งหนึ่ง",
        "ข้ามเป้าหมายไปก่อน เพิ่มได้ทุกเมื่อจากโปรไฟล์ แล้วเราจะสร้างแผนให้",
        "เรียนตามจังหวะของฉัน",
    ),
    "tr": s(
        "Hedefiniz nedir?",
        "Kişiselleştirilmiş bir öğrenme yolu oluşturmamıza yardımcı olur.",
        "Hedef ve seviye",
        "Hedef",
        "Mevcut seviye",
        "Zaman çizelgesi",
        "Henüz hedef tarih yok",
        "{{date}} tarihine kadar",
        "Seçilmedi — daha sonra profilden ekleyebilirsiniz",
        "Önce bir ders deneyerek başlayacağım",
        "Hedefi şimdilik atlayın. İstediğiniz zaman profilden ekleyebilirsiniz; o zaman bir yol haritası oluştururuz.",
        "Kendi hızımda öğreniyorum",
    ),
    "uk": s(
        "Яка у вас мета?",
        "Це допомагає нам створити персоналізований шлях навчання.",
        "Мета та рівень",
        "Мета",
        "Поточний рівень",
        "Терміни",
        "Ще немає цільової дати",
        "До {{date}}",
        "Не вибрано — можна додати пізніше в профілі",
        "Почну з пробного уроку",
        "Поки що пропустіть мету. Додати можна будь-коли в профілі — тоді побудуємо план.",
        "Навчаюся у власному темпі",
    ),
    "vi": s(
        "Mục tiêu của bạn là gì?",
        "Giúp chúng tôi tạo lộ trình học cá nhân hóa.",
        "Mục tiêu & trình độ",
        "Mục tiêu",
        "Trình độ hiện tại",
        "Mốc thời gian",
        "Chưa có ngày mục tiêu",
        "Trước {{date}}",
        "Chưa chọn — có thể thêm sau trong hồ sơ",
        "Tôi sẽ bắt đầu bằng một buổi học thử",
        "Bỏ qua mục tiêu tạm thời. Bạn có thể thêm bất cứ lúc nào trong hồ sơ; khi đó chúng tôi sẽ lập lộ trình.",
        "Học theo nhịp của riêng tôi",
    ),
    "zh": s(
        "你的目标是什么？",
        "帮助我们为你创建个性化学习路径。",
        "目标与水平",
        "目标",
        "当前水平",
        "时间安排",
        "尚未设置目标日期",
        "{{date}} 前",
        "未选择 — 可稍后在个人资料中补充",
        "我先试上一节课",
        "暂时跳过目标。你随时可在个人资料中添加，届时我们会生成学习路线。",
        "按自己的节奏学习",
    ),
}

LANG: dict[str, dict[str, object]] = {
    "ar": ls(
        "اختر لغة التطبيق المفضلة لديك",
        "اختر لغتك",
        "اضبط لغة الواجهة",
        "ابدأ بلغتك",
        "لغة واحدة في كل التطبيق",
        "واصل بلغتك المفضلة",
    ),
    "cs": ls(
        "Zvolte preferovaný jazyk aplikace",
        "Zvolte svůj jazyk",
        "Nastavte jazyk rozhraní",
        "Začněte ve svém jazyce",
        "Jeden jazyk v celé aplikaci",
        "Pokračujte v preferovaném jazyce",
    ),
    "da": ls(
        "Vælg dit foretrukne appsprog",
        "Vælg dit sprog",
        "Indstil grænsefladesproget",
        "Start på dit sprog",
        "Ét sprog i hele appen",
        "Fortsæt på dit foretrukne sprog",
    ),
    "de": ls(
        "Wählen Sie Ihre bevorzugte App-Sprache",
        "Wählen Sie Ihre Sprache",
        "Stellen Sie die Oberflächensprache ein",
        "Starten Sie in Ihrer Sprache",
        "Eine Sprache in der gesamten App",
        "Weiter in Ihrer bevorzugten Sprache",
    ),
    "el": ls(
        "Επιλέξτε την προτιμώμενη γλώσσα εφαρμογής",
        "Επιλέξτε τη γλώσσα σας",
        "Ορίστε τη γλώσσα διεπαφής",
        "Ξεκινήστε στη γλώσσα σας",
        "Μία γλώσσα σε όλη την εφαρμογή",
        "Συνεχίστε στην προτιμώμενη γλώσσα",
    ),
    "es": ls(
        "Elige el idioma preferido de la app",
        "Elige tu idioma",
        "Configura el idioma de la interfaz",
        "Empieza en tu idioma",
        "Un solo idioma en toda la app",
        "Continúa en tu idioma preferido",
    ),
    "fa": ls(
        "زبان رابط کاربری را انتخاب کنید",
        "زبان خود را انتخاب کنید",
        "رابط را به فارسی تنظیم کنید",
        "همین حالا زبان را انتخاب کنید",
        "یک زبان در سراسر برنامه",
        "به زبان دلخواه ادامه دهید",
    ),
    "fi": ls(
        "Valitse sovelluksen kieli",
        "Valitse kielesi",
        "Aseta käyttöliittymän kieli",
        "Aloita omalla kielelläsi",
        "Yksi kieli koko sovelluksessa",
        "Jatka valitsemallasi kielellä",
    ),
    "fr": ls(
        "Choisissez la langue de l'application",
        "Choisissez votre langue",
        "Réglez la langue de l'interface",
        "Commencez dans votre langue",
        "Une langue pour toute l'application",
        "Continuez dans votre langue préférée",
    ),
    "he": ls(
        "בחרו את שפת הממשק המועדפת",
        "בחרו את השפה שלכם",
        "הגדירו את שפת הממשק",
        "התחילו בשפה שלכם",
        "שפה אחת בכל האפליקציה",
        "המשיכו בשפה המועדפת",
    ),
    "hi": ls(
        "ऐप की अपनी पसंदीदा भाषा चुनें",
        "अपनी भाषा चुनें",
        "इंटरफ़ेस भाषा सेट करें",
        "अपनी भाषा में शुरू करें",
        "पूरे ऐप में एक भाषा",
        "अपनी पसंदीदा भाषा में जारी रखें",
    ),
    "id": ls(
        "Pilih bahasa aplikasi pilihan Anda",
        "Pilih bahasa Anda",
        "Atur bahasa antarmuka",
        "Mulai dalam bahasa Anda",
        "Satu bahasa di seluruh aplikasi",
        "Lanjutkan dalam bahasa pilihan",
    ),
    "it": ls(
        "Scegli la lingua preferita dell'app",
        "Scegli la tua lingua",
        "Imposta la lingua dell'interfaccia",
        "Inizia nella tua lingua",
        "Una lingua in tutta l'app",
        "Continua nella lingua preferita",
    ),
    "ja": ls(
        "アプリの表示言語を選んでください",
        "言語を選択してください",
        "インターフェース言語を設定",
        "あなたの言語で始める",
        "アプリ全体で同じ言語",
        "お好みの言語で続ける",
    ),
    "ko": ls(
        "앱에서 사용할 언어를 선택하세요",
        "언어를 선택하세요",
        "인터페이스 언어를 설정하세요",
        "내 언어로 시작하기",
        "앱 전체에서 하나의 언어",
        "선호하는 언어로 계속하기",
    ),
    "ms": ls(
        "Pilih bahasa aplikasi pilihan anda",
        "Pilih bahasa anda",
        "Tetapkan bahasa antara muka",
        "Mula dalam bahasa anda",
        "Satu bahasa untuk keseluruhan aplikasi",
        "Teruskan dalam bahasa pilihan",
    ),
    "nl": ls(
        "Kies je voorkeurstaal voor de app",
        "Kies je taal",
        "Stel de interfacetaal in",
        "Begin in je eigen taal",
        "Eén taal in de hele app",
        "Ga verder in je voorkeurstaal",
    ),
    "no": ls(
        "Velg foretrukket appspråk",
        "Velg språket ditt",
        "Angi grensesnittspråk",
        "Start på språket ditt",
        "Ett språk i hele appen",
        "Fortsett på foretrukket språk",
    ),
    "pl": ls(
        "Wybierz preferowany język aplikacji",
        "Wybierz swój język",
        "Ustaw język interfejsu",
        "Zacznij w swoim języku",
        "Jeden język w całej aplikacji",
        "Kontynuuj w preferowanym języku",
    ),
    "pt": ls(
        "Escolha o idioma preferido do app",
        "Escolha seu idioma",
        "Defina o idioma da interface",
        "Comece no seu idioma",
        "Um idioma em todo o aplicativo",
        "Continue no idioma preferido",
    ),
    "ro": ls(
        "Alegeți limba preferată a aplicației",
        "Alegeți limba dvs.",
        "Setați limba interfeței",
        "Începeți în limba dvs.",
        "O singură limbă în tot restul aplicației",
        "Continuați în limba preferată",
    ),
    "ru": ls(
        "Выберите язык интерфейса приложения",
        "Выберите ваш язык",
        "Настройте язык интерфейса",
        "Начните на своём языке",
        "Один язык во всём приложении",
        "Продолжите на предпочитаемом языке",
    ),
    "sv": ls(
        "Välj önskat appspråk",
        "Välj ditt språk",
        "Ställ in gränssnittsspråk",
        "Börja på ditt språk",
        "Ett språk i hela appen",
        "Fortsätt på ditt föredragna språk",
    ),
    "th": ls(
        "เลือกภาษาที่ต้องการใช้ในแอป",
        "เลือกภาษาของคุณ",
        "ตั้งค่าภาษาของอินเทอร์เฟซ",
        "เริ่มต้นด้วยภาษาของคุณ",
        "ภาษาเดียวทั้งแอป",
        "ดำเนินต่อด้วยภาษาที่ต้องการ",
    ),
    "tr": ls(
        "Uygulama için tercih ettiğiniz dili seçin",
        "Dilinizi seçin",
        "Arayüz dilini ayarlayın",
        "Kendi dilinizde başlayın",
        "Tüm uygulamada tek dil",
        "Tercih ettiğiniz dilde devam edin",
    ),
    "uk": ls(
        "Оберіть бажану мову інтерфейсу застосунку",
        "Виберіть вашу мову",
        "Налаштуйте мову інтерфейсу",
        "Почніть своєю мовою",
        "Одна мова в усьому застосунку",
        "Продовжуйте обраною мовою",
    ),
    "vi": ls(
        "Chọn ngôn ngữ ưa thích cho ứng dụng",
        "Chọn ngôn ngữ của bạn",
        "Đặt ngôn ngữ giao diện",
        "Bắt đầu bằng ngôn ngữ của bạn",
        "Một ngôn ngữ cho toàn bộ ứng dụng",
        "Tiếp tục bằng ngôn ngữ ưa thích",
    ),
    "zh": ls(
        "选择你在应用中使用的语言",
        "选择你的语言",
        "设置界面语言",
        "用你的语言开始",
        "全应用统一语言",
        "使用你偏好的语言继续",
    ),
}

A11Y: dict[str, str] = {
    "ar": "التنقل بين الخطوات",
    "cs": "Kroková navigace",
    "da": "Trinnavigation",
    "de": "Schrittnavigation",
    "el": "Πλοήγηση βημάτων",
    "es": "Navegación por pasos",
    "fa": "پیمایش گام‌ها",
    "fi": "Askelnavigointi",
    "fr": "Navigation par étapes",
    "he": "ניווט בין שלבים",
    "hi": "चरण नेविगेशन",
    "id": "Navigasi langkah",
    "it": "Navigazione passi",
    "ja": "ステップのナビゲーション",
    "ko": "단계 탐색",
    "ms": "Navigasi langkah",
    "nl": "Stapnavigatie",
    "no": "Trinnnavigasjon",
    "pl": "Nawigacja kroków",
    "pt": "Navegação por passos",
    "ro": "Navigare pe pași",
    "ru": "Пошаговая навигация",
    "sv": "Stegnavigering",
    "th": "การนำทางขั้นตอน",
    "tr": "Adım gezintisi",
    "uk": "Покрокова навігація",
    "vi": "Điều hướng theo bước",
    "zh": "步骤导航",
}


def main() -> None:
    codes = sorted(set(WELCOME.keys()) | set(STUDENT.keys()) | set(LANG.keys()) | set(A11Y.keys()))
    packs: dict[str, dict[str, object]] = {}
    for c in codes:
        entry: dict[str, object] = {
            "s": STUDENT[c],
            "ls": LANG[c],
            "a11y": A11Y[c],
        }
        if c not in W_SKIP:
            entry["w"] = WELCOME[c]
        packs[c] = entry
    OUT.write_text(json.dumps(packs, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("Wrote", OUT, "keys:", len(packs))


if __name__ == "__main__":
    main()
