services:
  - type: web
    name: languager-backend
    rootDir: backend
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: development
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: AUTH0_DOMAIN
        sync: false
      - key: AUTH0_AUDIENCE
        sync: false
      - key: AGORA_APP_ID
        sync: false
      - key: AGORA_APP_CERT
        sync: false
      - key: AGORA_TEMP_TOKEN
        sync: false
      - key: GOOGLE_CLOUD_BUCKET_NAME
        sync: false
      - key: GOOGLE_CLOUD_PROJECT_ID
        sync: false
      - key: GOOGLE_CLOUD_KEY_FILE
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false

  - type: web
    name: languager-frontend
    env: static
    rootDir: language-learning-app
    buildCommand: npm ci && npm run build
    staticPublishPath: www
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
